export const editing=new URLSearchParams(location.search).get('edit')==='1';
export let data={version:1,locations:[]};
let selected,changed,db,queue=Promise.resolve(),adding=false;
const $=s=>document.querySelector(s);
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text)n.textContent=text;if(cls)n.className=cls;return n;};
export function validate(value){
 if(value?.version!==1||!Array.isArray(value.locations)||value.locations.length>500)throw Error('Fișier invalid: sunt acceptate maximum 500 de locații.');
 const ids=new Set();return {version:1,locations:value.locations.map(p=>{
 if(!p||typeof p.id!=='string'||!p.id||ids.has(p.id)||typeof p.name!=='string'||!p.name.trim()||p.name.length>100||!Number.isFinite(p.u)||!Number.isFinite(p.v)||p.u<0||p.u>1||p.v<0||p.v>1)throw Error('Locație invalidă sau ID duplicat.');ids.add(p.id);
 for(const [key,max] of [['type',60],['description',2000],['lore',50000]])if(typeof p[key]!=='string'||p[key].length>max)throw Error('Câmp invalid: '+key);
 if(!Array.isArray(p.images)||p.images.length>8||p.images.some(i=>typeof i!=='string'||i.length>2000000||!/^data:image\/(jpeg|png|webp);base64,[A-Za-z0-9+/=]+$/.test(i)))throw Error('Imagini invalide.');
 return {id:p.id,name:p.name,type:p.type,u:p.u,v:p.v,description:p.description,lore:p.lore,images:[...p.images]};})};
}
function status(text,error=false){const n=$('#save-state');if(n){n.textContent=text;n.classList.toggle('error',error);}}
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open('seraphelion-lore',1);r.onupgradeneeded=()=>r.result.createObjectStore('drafts');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
function readDraft(){return new Promise((resolve,reject)=>{const r=db.transaction('drafts').objectStore('drafts').get('atlas');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
function persist(){status('Se salvează…');const snapshot=structuredClone(data);queue=queue.catch(()=>{}).then(()=>new Promise((resolve,reject)=>{if(!db){reject(Error('Stocare indisponibilă'));return;}const tx=db.transaction('drafts','readwrite');tx.objectStore('drafts').put(snapshot,'atlas');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);}));queue.then(()=>status('Ciornă salvată în acest browser'),()=>status('Salvarea locală nu a reușit. Exportă ciorna pentru a o păstra.',true));}
function update(){persist();changed();}
function notice(text){$('#editor-message').textContent=text;}
export async function initLore(onChange){changed=onChange;const response=await fetch('./locations.json',{cache:'no-cache'});if(!response.ok)throw Error('Nu s-au putut încărca locațiile.');data=validate(await response.json());
 $('#detail').replaceChildren();$('#detail').setAttribute('aria-label','Fișa locației');
 const link=el('a',editing?'Înapoi la harta publică':'Editor de lore','editor-link');link.href=editing?'./':'?edit=1';document.body.append(link);
 if(editing){document.body.classList.add('editing');const bar=el('section',null,'editor-bar');bar.setAttribute('aria-label','Editor de lore');
 const heading=el('strong','Editor de lore');const hint=el('p','Ciorne locale. Exportă locations.json și încarcă-l în repository pentru a publica. Nu introduce aici informații secrete de DM.');
 const state=el('span','Ciornă locală');state.id='save-state';state.setAttribute('role','status');
 const select=el('select');select.id='location-picker';select.setAttribute('aria-label','Alege locația');select.onchange=()=>openPlace(select.value);
 const add=el('button','Adaugă locație');add.id='add-location';add.onclick=()=>{adding=!adding;add.textContent=adding?'Anulează plasarea':'Adaugă locație';notice(adding?'Apasă pe hartă pentru a poziționa noua locație.':'');};
 const exp=el('button','Exportă pentru publicare');exp.onclick=()=>{const blob=new Blob([JSON.stringify(validate(data),null,2)],{type:'application/json'});const a=el('a');a.href=URL.createObjectURL(blob);a.download='locations.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);notice('În GitHub: Add file → Upload files → alege locations.json → Commit changes. Publicarea se actualizează automat.');};
 const impLabel=el('label','Importă ciornă','import-label');const imp=el('input');imp.type='file';imp.accept='.json,application/json';imp.setAttribute('aria-label','Importă fișierul de lore');imp.onchange=async()=>{try{const f=imp.files[0];if(!f)return;if(f.size>24*1024*1024)throw Error('Fișierul depășește 24 MB.');const next=validate(JSON.parse(await f.text()));if(!confirm('Înlocuiești ciorna locală cu fișierul ales? Exportă mai întâi ciorna dacă vrei să o păstrezi.'))return;data=next;selected=null;update();refreshPicker();if(data.locations.length)openPlace(data.locations[0].id);else $('#detail').hidden=true;notice('Ciornă importată.');}catch(e){notice(e.message);}finally{imp.value='';}};impLabel.append(imp);
 const publish=el('a','Deschide repository-ul');publish.href='https://github.com/Pavel1Eryndor/seraphelion-map';publish.target='_blank';publish.rel='noopener';
 const message=el('p');message.id='editor-message';message.setAttribute('role','status');bar.append(heading,hint,select,add,exp,impLabel,publish,state,message);document.body.append(bar);
 try{db=await openDB();const draft=await readDraft();if(draft){data=validate(draft);status('Ciornă locală restaurată');}else status('Versiunea publicată · editează pentru a crea o ciornă');}catch{status('Stocarea locală nu este disponibilă. Exportă înainte de a închide.',true);}
 refreshPicker();if(data.locations.length)openPlace(data.locations[0].id);
 }
 document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(adding){adding=false;$('#add-location').textContent='Adaugă locație';notice('');}else $('#detail').hidden=true;}});
}
function refreshPicker(){const s=$('#location-picker');if(!s)return;s.replaceChildren(...data.locations.map(p=>{const o=el('option',p.name);o.value=p.id;return o;}));if(selected)s.value=selected;}
export function placeAt(u,v){if(!editing||!adding)return false;if(data.locations.length>=500){notice('Limita este de 500 de locații.');return true;}const p={id:crypto.randomUUID(),name:'Locație nouă',type:'Punct de interes',u,v,description:'',lore:'',images:[]};data.locations.push(p);adding=false;$('#add-location').textContent='Adaugă locație';notice('Locație adăugată. Completează fișa ei.');update();refreshPicker();openPlace(p.id);return true;}
export function isPlacing(){return adding;}
export function openPlace(id){const p=data.locations.find(x=>x.id===id);if(!p)return;selected=id;refreshPicker();const panel=$('#detail');panel.hidden=false;panel.replaceChildren();const close=el('button','×');close.id='close';close.setAttribute('aria-label','Închide detaliile');close.onclick=()=>{panel.hidden=true;};panel.append(close,el('span',editing?'EDITEAZĂ LOCAȚIA':p.type.toUpperCase(),'eyebrow'));
 if(!editing){panel.append(el('h2',p.name));if(p.description)panel.append(el('p',p.description,'place-description'));if(p.images.length){const gallery=el('div',null,'lore-gallery');p.images.forEach((src,i)=>{const a=el('a');a.href=src;a.download=p.id+'-'+(i+1)+'.jpg';const img=el('img');img.src=src;img.alt=p.name+' — imagine '+(i+1);img.loading='lazy';a.append(img);gallery.append(a);});panel.append(gallery);}if(p.lore)panel.append(el('h3','Povestea locului'),el('p',p.lore,'lore-text'));if(!p.description&&!p.lore&&!p.images.length)panel.append(el('p','Povestea acestui loc nu a fost încă adăugată.'));return;}
 for(const [key,title,max,rows] of [['name','Nume',100,0],['type','Tipul locației',60,0],['description','Descriere scurtă',2000,3],['lore','Lore și informații',50000,10]]){const label=el('label',title);const input=el(rows?'textarea':'input');input.value=p[key];input.maxLength=max;input.id='field-'+key;if(rows)input.rows=rows;label.htmlFor=input.id;input.oninput=()=>{p[key]=input.value;if(key==='name'){p.name=input.value.trim()||'Locație fără nume';refreshPicker();}update();};panel.append(label,input);}
 panel.append(el('h3','Poze'));const gallery=el('div',null,'lore-gallery');const renderImages=()=>{gallery.replaceChildren();p.images.forEach((src,i)=>{const card=el('div');const img=el('img');img.src=src;img.alt='Imagine '+(i+1)+' pentru '+p.name;const remove=el('button','Elimină imaginea '+(i+1));remove.onclick=()=>{p.images.splice(i,1);update();renderImages();};card.append(img,remove);gallery.append(card);});};renderImages();panel.append(gallery);
 const upload=el('input');upload.type='file';upload.accept='image/jpeg,image/png,image/webp';upload.multiple=true;upload.id='location-photos';const label=el('label','Adaugă poze (JPG, PNG, WebP)');label.htmlFor=upload.id;const msg=el('p','Maximum 8 poze per locație, 10 MB per fișier. Prima este imaginea principală.');msg.className='photo-note';msg.setAttribute('role','status');upload.onchange=async()=>{upload.disabled=true;try{for(const f of upload.files){if(p.images.length>=8)throw Error('Ai atins limita de 8 poze.');if(f.size>10*1024*1024)throw Error('Imagine prea mare: '+f.name);if(!['image/jpeg','image/png','image/webp'].includes(f.type))throw Error('Format neacceptat.');const bitmap=await createImageBitmap(f);const scale=Math.min(1,1280/Math.max(bitmap.width,bitmap.height));const c=document.createElement('canvas');c.width=Math.round(bitmap.width*scale);c.height=Math.round(bitmap.height*scale);c.getContext('2d').drawImage(bitmap,0,0,c.width,c.height);bitmap.close();p.images.push(c.toDataURL('image/jpeg',.8));update();renderImages();}msg.textContent='Pozele au fost adăugate în ciornă.';}catch(e){msg.textContent=e.message;}finally{upload.disabled=false;upload.value='';}};panel.append(label,upload,msg);
}
